### ISSUE TITLE
fastq-sample segfault

### ISSUE THREAD

**Issue by moskalenko** [dcjones/fastq-tools#13]
fastq-sample segfaults while subsampling a couple of fastq files:

fastq-sample -n 900000 -o subsample first.fastq second.fastq

...

open("subsample.2.fastq", O_WRONLY|O_CREAT|O_EXCL, 0600) = 6
fcntl(6, F_GETFL)                       = 0x8001 (flags O_WRONLY|O_LARGEFILE)
fstat(6, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
mmap(NULL, 2097152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2aefcc06d000
lseek(6, 0, SEEK_CUR)                   = 0
read(3, "@NS500162:92:H2L22BGXX:1:11101:4"..., 2097152) = 2097152
read(4, "@NS500162:92:H2L22BGXX:1:11101:4"..., 2097152) = 2097152
read(3, "CATCGCCCTG\n+\nAAAAAFFFFFFFFFFFFFF"..., 2097152) = 2097152
read(4, "FAAFFF<FFFFFFFFFFFFFFFFAFFFFAFFF"..., 2097152) = 2097152
read(3, ".FAFFFFA7FF<AAFFFFFFFFF7FF.FFFFF"..., 2097152) = 2097152
read(4, "TTGAAGCCGAGGACACGGTCCGCACCCTGCGT"..., 2097152) = 2097152
read(3, "CCCCGCTGGGCTCACCCACCAACTGGTGCGTG"..., 2097152) = 2097152
read(4, "CAAGGCGTACGCGCTCCACCGTCTCGGATGAA"..., 2097152) = 2097152
read(3, "AAACAGCGTTGATTCGTAC\n+\n<<AAAFFFFF"..., 2097152) = 2097152
read(4, "CAGGGCCTGCTCCCACACCTCGGGC\n+\n<A<<"..., 2097152) = 2097152
read(3, "101:18886:16172 1:N:0:6\nACAAACAT"..., 2097152) = 2097152
read(4, "FF<FAFFFF7)FFAF7F\n@NS500162:92:H"..., 2097152) = 2097152
read(3, "))AF77AFF..<<F7.FF.\n@NS500162:92"..., 2097152) = 2097152
read(4, "F.FF<AAA<F.FF.AAF<AFFF7F<F)<AF7F"..., 2097152) = 2097152
read(3, "CGCCCAGACATCGTCC\n+\nAAAAA<FFFF<FF"..., 2097152) = 2097152
read(4, "62:92:H2L22BGXX:1:11102:21189:35"..., 2097152) = 2097152
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++

GDB backtrace:

(gdb) bt
#0  0x00000039ad244289 in vfprintf () from /lib64/libc.so.6
#1  0x00000039ad24f368 in fprintf () from /lib64/libc.so.6
#2  0x0000000000401347 in fastq_sample (rng_seed=13, prefix=0x605af0 "\204,\255", <incomplete sequence \373>, cprefix=0xd <Address 0xd out of bounds>, file1=<value optimized out>,
    file2=<value optimized out>, k=900000, p=3.1170878272885916e-317) at fastq-sample.c:253
#3  0x000000000040192d in main (argc=7, argv=0x7fffffffd5f8) at fastq-sample.c:384

**Comment by moskalenko** [comment]
Both files can be processed individually without issues.

**Comment by dcjones** [comment]
I think this has been fixed on master for a while but I neglected to tag a new version. I just did so, so you can try 0.8 here: http://homes.cs.washington.edu/~dcjones/fastq-tools/fastq-tools-0.8.tar.gz
